-- ============================================================
-- Migration: .data/db.json → MySQL
-- Generated: 2026-08-03T12:06:59.619Z
-- ============================================================
SET FOREIGN_KEY_CHECKS=0;

-- Workflows (1 rows)
INSERT INTO Workflows (WorkflowID, WorkflowName, WorkflowSlug, Category, Description, Icon, Color, Version, PublishedVersion, SlaTotalHours, ReactFlowGraphJson, FieldsJson, StepsJson, Status, IsArchived, DateCreated, DateUpdated) VALUES ('wf_1785070874349', 'Form Tets', 'form-tets', 'HR', 'Custom workflow form created via Enterprise Form Builder', '📋', '#4F46E5', 1, 1, 48, NULL, '[{"id":"f-1785069709738","label":"العدد","key":"field_9738","type":"number","section":"General Request Details","width":"half","required":true,"readOnly":false,"placeholder":"","hasCondition":false,"visibleToRequester":true,"visibleToApproversOnly":false},{"id":"f-1785069700368","label":"Long Text / Notes","key":"long_text_notes_2","type":"textarea","section":"General Request Details","width":"full","required":true,"readOnly":false,"placeholder":"","hasCondition":false,"visibleToRequester":true,"visibleToApproversOnly":false}]', '[{"id":"step-1","workflow_id":"wf_form-tets","react_flow_node_id":"node-step-1","name":"Department Manager","step_order":1,"step_type":"approval","execution_mode":"sequential","assignee_type":"manager_of_requester","assignee_value":"Direct Manager","ola_hours":4,"notify_on_assign":true,"notify_on_complete":false,"sort":1},{"id":"step-2","workflow_id":"wf_form-tets","react_flow_node_id":"node-step-2","name":"Department Head / Finance Review","step_order":2,"step_type":"approval","execution_mode":"sequential","assignee_type":"role","assignee_value":"Finance Manager","ola_hours":8,"notify_on_assign":true,"notify_on_complete":false,"sort":2}]', 'published', 0, '2026-07-26 13:01:14', '2026-07-26 13:01:14') ON DUPLICATE KEY UPDATE WorkflowName=VALUES(WorkflowName), DateUpdated=VALUES(DateUpdated);

-- Tickets (1 rows)
INSERT INTO Tickets (TicketID, TicketNumber, WorkflowID, WorkflowVersion, WorkflowSnapshotJson, RequesterUserID, RequesterName, Title, Priority, Status, CurrentStepNodeID, CurrentStepOrder, CurrentAssigneesJson, SubmittedAt, SlaDeadline, OlaDeadline, OlaAccumulatedPauseMs, DateCreated, DateUpdated) VALUES ('req_1785069809233', 'REQ-2026-99781', 'wf_1785069771800', 1, '[{"id":"step-1","workflow_id":"wf_form-tets","react_flow_node_id":"node-step-1","name":"Department Manager","step_order":1,"step_type":"approval","execution_mode":"sequential","assignee_type":"manager_of_requester","assignee_value":"Direct Manager","ola_hours":4,"notify_on_assign":true,"notify_on_complete":false,"sort":1},{"id":"step-2","workflow_id":"wf_form-tets","react_flow_node_id":"node-step-2","name":"Department Head / Finance Review","step_order":2,"step_type":"approval","execution_mode":"sequential","assignee_type":"role","assignee_value":"Finance Manager","ola_hours":8,"notify_on_assign":true,"notify_on_complete":false,"sort":2}]', 'Ahmed Mohamed (IT Staff)', 'Ahmed Mohamed (IT Staff)', 'Form Tets Request', 'normal', 'pending', 'node-step-2', 2, '["Finance Manager"]', '2026-07-26 12:43:29', '2026-07-28 12:43:29', '2026-07-26 20:50:34', 0, '2026-07-26 12:43:29', '2026-07-26 12:50:34') ON DUPLICATE KEY UPDATE Status=VALUES(Status), DateUpdated=VALUES(DateUpdated);

-- TicketValues (3 rows)
INSERT INTO TicketValues (TicketValueID, TicketID, FieldKey, ValueText, ValueNumber) VALUES ('val_1785069809233_29ag6', 'req_1785069809233', 'field_8779', 'تجربة', NULL) ON DUPLICATE KEY UPDATE ValueText=VALUES(ValueText);
INSERT INTO TicketValues (TicketValueID, TicketID, FieldKey, ValueText, ValueNumber) VALUES ('val_1785069809234_u5ou8', 'req_1785069809233', 'field_9738', '2', 2) ON DUPLICATE KEY UPDATE ValueText=VALUES(ValueText);
INSERT INTO TicketValues (TicketValueID, TicketID, FieldKey, ValueText, ValueNumber) VALUES ('val_1785069809234_5meru', 'req_1785069809233', 'long_text_notes_2', 'تجربة', NULL) ON DUPLICATE KEY UPDATE ValueText=VALUES(ValueText);

-- ApprovalLog (2 rows)
INSERT INTO ApprovalLog (ApprovalLogID, TicketID, StepNodeID, StepOrderSnapshot, ActorUserID, ActorUserName, Action, Comments, DecisionAt) VALUES ('log_1785069809234', 'req_1785069809233', 'node-step-1', 1, 'Ahmed Mohamed', 'Ahmed Mohamed', 'submitted', 'Request submitted and routed automatically to first approval step.', '2026-07-26 12:43:29') ON DUPLICATE KEY UPDATE Action=VALUES(Action);
INSERT INTO ApprovalLog (ApprovalLogID, TicketID, StepNodeID, StepOrderSnapshot, ActorUserID, ActorUserName, Action, Comments, DecisionAt) VALUES ('log_1785070234220', 'req_1785069809233', 'node-step-2', 2, 'Ahmed Mohamed', 'Ahmed Mohamed', 'approved', 'Decision: approved', '2026-07-26 12:50:34') ON DUPLICATE KEY UPDATE Action=VALUES(Action);

SET FOREIGN_KEY_CHECKS=1;
-- Migration complete.